---
volumes:
  - device: /dev/vdb
    mountpoint: /var/lib/docker
  - device: /dev/vdd
    mountpoint: /data

proxy_environment:
  - key: http_proxy 
    value : http://wwwproxy.unimelb.edu.au:8000/  
  - key: https_proxy 
    value : http://wwwproxy.unimelb.edu.au:8000/
  - key: no_proxy 
    value : "localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"
  - key: HTTP_PROXY 
    value : http://wwwproxy.unimelb.edu.au:8000/
  - key: HTTPS_PROXY
    value : http://wwwproxy.unimelb.edu.au:8000/

couchdb_dir: couchdb
#couchdb_version: developer-preview-2.0
couchdb_install_dir: /home/ubuntu/couchdb
ansible_distribution: ubuntu
ansible_distribution_release: bionic

local_submodules_dir: ../../../../submodules
local_config_dir: ../../../../config
docker_proxy_dir: /etc/systemd/system/docker.service.d
docker_http_proxy_file: http-proxy.conf
docker_https_proxy_file: https-proxy.conf